// Convergence v0.11 - items only. Advancements removed; Patchouli is the progression UI.
const CV11_ITEMS = [
  "incomplete_arcane_mechanism",
  "convergence_manual_binding",
  "cross_discipline_adapter",
  "bridge_matrix_t1",
  "bridge_matrix_t2",
  "bridge_matrix_t3",
  "bridge_matrix_t4",
  "bridge_matrix_t5",
  "bridge_matrix_t6",
  "bridge_matrix_t7",
  "bridge_matrix_t8",
  "modular_upgrade_schematic",
  "midgame_convergence_ledger",
  "late_game_integration_deed",
  "endgame_assembly_mandate",
  "universal_recipe_matrix",
  "final_assembly_singularity",
  "kinetic_magic_logistics_key",
  "power_industry_void_key",
  "bio_settlement_hunt_key",
  "aero_travel_builder_key",
  "worldforged_convergence_core",
  "resonant_machine_frame",
  "dimensional_matrix",
  "unified_automation_core",
  "source_treated_alloy",
  "arcane_mechanism",
  "runic_logic_processor",
  "energized_control_circuit",
  "industrial_servo",
  "spirit_actuator",
  "verdant_automation_core",
  "kinetic_calibrator",
  "stress_frame",
  "gear_logic",
  "casing_stamp",
  "belt_sync",
  "precision_actuator",
  "deploy_sequence_card",
  "factory_timing_unit",
  "contraption_manifold",
  "trainyard_route_token",
  "overstressed_safety_valve",
  "creative_kinetic_key",
  "source_lens",
  "glyphic_circuit",
  "ritual_inscriber",
  "spellbound_coil",
  "imbuement_focus",
  "source_coupler",
  "sourcelink_regulator",
  "spell_matrix",
  "wixie_work_order",
  "ritual_gateway_key",
  "archmage_spell_spine",
  "creative_source_key",
  "quartz_logic_wafer",
  "fluix_memory_lattice",
  "channel_marker",
  "me_cable_tag",
  "storage_cell_ticket",
  "pattern_bus_array",
  "crafting_coprocessor_matrix",
  "autocraft_policy_card",
  "wireless_access_cipher",
  "quantum_link_contract",
  "me_singularity_lattice",
  "creative_logistics_key",
  "dielectric_regulator",
  "capacitor_bank_coil",
  "metallurgic_bus",
  "enriched_energy_cell",
  "alloy_reinforcement_ticket",
  "energy_control_logic",
  "battery_backplane",
  "reactor_access_card",
  "qio_sync_crystal",
  "fusion_alignment_ring",
  "nitro_flux_singularity",
  "creative_energy_key",
  "treated_machine_plate",
  "coke_calibrated_gear",
  "fluid_manifold",
  "conveyor_license",
  "wirecoil_relay",
  "steel_tooling_die",
  "greenhouse_controller",
  "factory_fluid_contract",
  "ore_drill_warrant",
  "machine_frame_charter",
  "supreme_frame_stamp",
  "creative_industry_key",
  "spirit_attunement_lens",
  "chalked_servo",
  "binding_contract",
  "otherstone_manifold",
  "iesnium_relay",
  "familiars_permit",
  "storage_spirit_writ",
  "ritual_safety_clause",
  "void_channel_key",
  "dimensional_storage_oath",
  "spirit_network_crown",
  "creative_void_key",
  "growth_lattice",
  "honeyed_logic_cell",
  "inferium_gene_sample",
  "botany_growth_plate",
  "prosperity_cultivar",
  "bee_routing_tag",
  "tertium_greenhouse_writ",
  "imperium_pollination_core",
  "supremium_life_matrix",
  "apiary_sovereignty_key",
  "worldseed_convergence_spore",
  "prudentium_cultivar",
  "insanium_life_matrix",
  "draconic_apiary_writ",
  "creative_bio_key",
  "kitchen_foundation_plan",
  "culinary_supply_manifest",
  "preservation_gasket",
  "settlement_ration_card",
  "stove_automation_token",
  "market_crate_manifest",
  "banquet_logistics_tag",
  "colony_storehouse_key",
  "comfort_supply_contract",
  "township_feast_writ",
  "server_catering_license",
  "creative_settlement_key",
  "explorer_survey",
  "ancient_component_shard",
  "ruined_blueprint_cache",
  "dungeon_route_map",
  "relic_appraisal_tag",
  "boss_trophy_writ",
  "nether_campaign_token",
  "end_campaign_token",
  "wild_hunt_relic",
  "ancient_conquest_key",
  "mythic_map_of_convergence",
  "creative_hunt_key",
  "balloon_rigging",
  "burner_valve",
  "lift_envelope_panel",
  "wind_gyroscope",
  "propeller_governor",
  "flight_stabilizer",
  "radar_transponder",
  "avionics_backplane",
  "cannon_synchronizer",
  "sky_command_cipher",
  "aerial_superiority_core",
  "creative_aero_key",
  "ender_anchor_crystal",
  "warp_attunement_rod",
  "compact_space_cell",
  "quantum_waystone_core",
  "spatial_fold_lens",
  "void_navigation_tablet",
  "interdimensional_bus",
  "planar_stabilizer",
  "voidbound_relay",
  "quantum_storage_seed",
  "planar_singularity",
  "creative_dimension_key",
  "mason_schematic",
  "decorative_fastener",
  "roofing_supply_order",
  "bridge_engineering_plan",
  "lamp_grid_relay",
  "furniture_batch_ticket",
  "gadget_calibration_plate",
  "structural_integrity_stamp",
  "compact_builder_rig",
  "infrastructure_master_key",
  "world_shape_matrix",
  "creative_builder_key"
];
const CV11_TRANSITIONALS = [
  "incomplete_gear_logic",
  "incomplete_precision_actuator",
  "incomplete_contraption_manifold",
  "incomplete_overstressed_safety_valve",
  "incomplete_ritual_inscriber",
  "incomplete_source_coupler",
  "incomplete_wixie_work_order",
  "incomplete_archmage_spell_spine",
  "incomplete_channel_marker",
  "incomplete_pattern_bus_array",
  "incomplete_wireless_access_cipher",
  "incomplete_me_singularity_lattice",
  "incomplete_metallurgic_bus",
  "incomplete_energy_control_logic",
  "incomplete_qio_sync_crystal",
  "incomplete_nitro_flux_singularity",
  "incomplete_fluid_manifold",
  "incomplete_steel_tooling_die",
  "incomplete_ore_drill_warrant",
  "incomplete_supreme_frame_stamp",
  "incomplete_binding_contract",
  "incomplete_familiars_permit",
  "incomplete_void_channel_key",
  "incomplete_spirit_network_crown",
  "incomplete_inferium_gene_sample",
  "incomplete_bee_routing_tag",
  "incomplete_supremium_life_matrix",
  "incomplete_worldseed_convergence_spore",
  "incomplete_preservation_gasket",
  "incomplete_market_crate_manifest",
  "incomplete_comfort_supply_contract",
  "incomplete_server_catering_license",
  "incomplete_ruined_blueprint_cache",
  "incomplete_boss_trophy_writ",
  "incomplete_wild_hunt_relic",
  "incomplete_mythic_map_of_convergence",
  "incomplete_lift_envelope_panel",
  "incomplete_flight_stabilizer",
  "incomplete_cannon_synchronizer",
  "incomplete_aerial_superiority_core",
  "incomplete_compact_space_cell",
  "incomplete_void_navigation_tablet",
  "incomplete_voidbound_relay",
  "incomplete_planar_singularity",
  "incomplete_roofing_supply_order",
  "incomplete_furniture_batch_ticket",
  "incomplete_compact_builder_rig",
  "incomplete_world_shape_matrix"
];
const CV11_NAMES = {
  "prudentium_cultivar": "Prudentium Cultivar",
  "insanium_life_matrix": "Insanium Life Matrix",
  "draconic_apiary_writ": "Draconic Apiary Writ",
  "convergence_manual_binding": "Convergence Manual Binding",
  "cross_discipline_adapter": "Cross-Discipline Adapter",
  "modular_upgrade_schematic": "Modular Upgrade Schematic",
  "midgame_convergence_ledger": "Midgame Convergence Ledger",
  "late_game_integration_deed": "Late-Game Integration Deed",
  "endgame_assembly_mandate": "Endgame Assembly Mandate",
  "universal_recipe_matrix": "Universal Recipe Matrix",
  "final_assembly_singularity": "Final Assembly Singularity",
  "kinetic_magic_logistics_key": "Kinetic-Magic-Logistics Key",
  "power_industry_void_key": "Power-Industry-Void Key",
  "bio_settlement_hunt_key": "Bio-Settlement-Hunt Key",
  "aero_travel_builder_key": "Aero-Travel-Builder Key",
  "worldforged_convergence_core": "Worldforged Convergence Core",
  "resonant_machine_frame": "Resonant Machine Frame",
  "dimensional_matrix": "Dimensional Matrix",
  "unified_automation_core": "Unified Automation Core",
  "source_treated_alloy": "Source-Treated Alloy",
  "arcane_mechanism": "Arcane Mechanism",
  "runic_logic_processor": "Runic Logic Processor",
  "energized_control_circuit": "Energized Control Circuit",
  "industrial_servo": "Industrial Servo",
  "spirit_actuator": "Spirit Actuator",
  "verdant_automation_core": "Verdant Automation Core",
  "kinetic_calibrator": "Kinetic Calibrator",
  "stress_frame": "Stress Frame",
  "gear_logic": "Gear Logic",
  "casing_stamp": "Casing Stamp",
  "belt_sync": "Belt Sync",
  "precision_actuator": "Precision Actuator",
  "deploy_sequence_card": "Deploy Sequence Card",
  "factory_timing_unit": "Factory Timing Unit",
  "contraption_manifold": "Contraption Manifold",
  "trainyard_route_token": "Trainyard Route Token",
  "overstressed_safety_valve": "Overstressed Safety Valve",
  "creative_kinetic_key": "Creative Kinetic Key",
  "source_lens": "Source Lens",
  "glyphic_circuit": "Glyphic Circuit",
  "ritual_inscriber": "Ritual Inscriber",
  "spellbound_coil": "Spellbound Coil",
  "imbuement_focus": "Imbuement Focus",
  "source_coupler": "Source Coupler",
  "sourcelink_regulator": "Sourcelink Regulator",
  "spell_matrix": "Spell Matrix",
  "wixie_work_order": "Wixie Work Order",
  "ritual_gateway_key": "Ritual Gateway Key",
  "archmage_spell_spine": "Archmage Spell Spine",
  "creative_source_key": "Creative Source Key",
  "quartz_logic_wafer": "Quartz Logic Wafer",
  "fluix_memory_lattice": "Fluix Memory Lattice",
  "channel_marker": "Channel Marker",
  "me_cable_tag": "Me Cable Tag",
  "storage_cell_ticket": "Storage Cell Ticket",
  "pattern_bus_array": "Pattern Bus Array",
  "crafting_coprocessor_matrix": "Crafting Coprocessor Matrix",
  "autocraft_policy_card": "Autocraft Policy Card",
  "wireless_access_cipher": "Wireless Access Cipher",
  "quantum_link_contract": "Quantum Link Contract",
  "me_singularity_lattice": "Me Singularity Lattice",
  "creative_logistics_key": "Creative Logistics Key",
  "dielectric_regulator": "Dielectric Regulator",
  "capacitor_bank_coil": "Capacitor Bank Coil",
  "metallurgic_bus": "Metallurgic Bus",
  "enriched_energy_cell": "Enriched Energy Cell",
  "alloy_reinforcement_ticket": "Alloy Reinforcement Ticket",
  "energy_control_logic": "Energy Control Logic",
  "battery_backplane": "Battery Backplane",
  "reactor_access_card": "Reactor Access Card",
  "qio_sync_crystal": "Qio Sync Crystal",
  "fusion_alignment_ring": "Fusion Alignment Ring",
  "nitro_flux_singularity": "Nitro Flux Singularity",
  "creative_energy_key": "Creative Energy Key",
  "treated_machine_plate": "Treated Machine Plate",
  "coke_calibrated_gear": "Coke Calibrated Gear",
  "fluid_manifold": "Fluid Manifold",
  "conveyor_license": "Conveyor License",
  "wirecoil_relay": "Wirecoil Relay",
  "steel_tooling_die": "Steel Tooling Die",
  "greenhouse_controller": "Greenhouse Controller",
  "factory_fluid_contract": "Factory Fluid Contract",
  "ore_drill_warrant": "Ore Drill Warrant",
  "machine_frame_charter": "Machine Frame Charter",
  "supreme_frame_stamp": "Supreme Frame Stamp",
  "creative_industry_key": "Creative Industry Key",
  "spirit_attunement_lens": "Spirit Attunement Lens",
  "chalked_servo": "Chalked Servo",
  "binding_contract": "Binding Contract",
  "otherstone_manifold": "Otherstone Manifold",
  "iesnium_relay": "Iesnium Relay",
  "familiars_permit": "Familiars Permit",
  "storage_spirit_writ": "Storage Spirit Writ",
  "ritual_safety_clause": "Ritual Safety Clause",
  "void_channel_key": "Void Channel Key",
  "dimensional_storage_oath": "Dimensional Storage Oath",
  "spirit_network_crown": "Spirit Network Crown",
  "creative_void_key": "Creative Void Key",
  "growth_lattice": "Growth Lattice",
  "honeyed_logic_cell": "Honeyed Logic Cell",
  "inferium_gene_sample": "Inferium Gene Sample",
  "botany_growth_plate": "Botany Growth Plate",
  "prosperity_cultivar": "Prosperity Cultivar",
  "bee_routing_tag": "Bee Routing Tag",
  "tertium_greenhouse_writ": "Tertium Greenhouse Writ",
  "imperium_pollination_core": "Imperium Pollination Core",
  "supremium_life_matrix": "Supremium Life Matrix",
  "apiary_sovereignty_key": "Apiary Sovereignty Key",
  "worldseed_convergence_spore": "Worldseed Convergence Spore",
  "creative_bio_key": "Creative Bio Key",
  "kitchen_foundation_plan": "Kitchen Foundation Plan",
  "culinary_supply_manifest": "Culinary Supply Manifest",
  "preservation_gasket": "Preservation Gasket",
  "settlement_ration_card": "Settlement Ration Card",
  "stove_automation_token": "Stove Automation Token",
  "market_crate_manifest": "Market Crate Manifest",
  "banquet_logistics_tag": "Banquet Logistics Tag",
  "colony_storehouse_key": "Colony Storehouse Key",
  "comfort_supply_contract": "Comfort Supply Contract",
  "township_feast_writ": "Township Feast Writ",
  "server_catering_license": "Server Catering License",
  "creative_settlement_key": "Creative Settlement Key",
  "explorer_survey": "Explorer Survey",
  "ancient_component_shard": "Ancient Component Shard",
  "ruined_blueprint_cache": "Ruined Blueprint Cache",
  "dungeon_route_map": "Dungeon Route Map",
  "relic_appraisal_tag": "Relic Appraisal Tag",
  "boss_trophy_writ": "Boss Trophy Writ",
  "nether_campaign_token": "Nether Campaign Token",
  "end_campaign_token": "End Campaign Token",
  "wild_hunt_relic": "Wild Hunt Relic",
  "ancient_conquest_key": "Ancient Conquest Key",
  "mythic_map_of_convergence": "Mythic Map Of Convergence",
  "creative_hunt_key": "Creative Hunt Key",
  "balloon_rigging": "Balloon Rigging",
  "burner_valve": "Burner Valve",
  "lift_envelope_panel": "Lift Envelope Panel",
  "wind_gyroscope": "Wind Gyroscope",
  "propeller_governor": "Propeller Governor",
  "flight_stabilizer": "Flight Stabilizer",
  "radar_transponder": "Radar Transponder",
  "avionics_backplane": "Avionics Backplane",
  "cannon_synchronizer": "Cannon Synchronizer",
  "sky_command_cipher": "Sky Command Cipher",
  "aerial_superiority_core": "Aerial Superiority Core",
  "creative_aero_key": "Creative Aero Key",
  "ender_anchor_crystal": "Ender Anchor Crystal",
  "warp_attunement_rod": "Warp Attunement Rod",
  "compact_space_cell": "Compact Space Cell",
  "quantum_waystone_core": "Quantum Waystone Core",
  "spatial_fold_lens": "Spatial Fold Lens",
  "void_navigation_tablet": "Void Navigation Tablet",
  "interdimensional_bus": "Interdimensional Bus",
  "planar_stabilizer": "Planar Stabilizer",
  "voidbound_relay": "Voidbound Relay",
  "quantum_storage_seed": "Quantum Storage Seed",
  "planar_singularity": "Planar Singularity",
  "creative_dimension_key": "Creative Dimension Key",
  "mason_schematic": "Mason Schematic",
  "decorative_fastener": "Decorative Fastener",
  "roofing_supply_order": "Roofing Supply Order",
  "bridge_engineering_plan": "Bridge Engineering Plan",
  "lamp_grid_relay": "Lamp Grid Relay",
  "furniture_batch_ticket": "Furniture Batch Ticket",
  "gadget_calibration_plate": "Gadget Calibration Plate",
  "structural_integrity_stamp": "Structural Integrity Stamp",
  "compact_builder_rig": "Compact Builder Rig",
  "infrastructure_master_key": "Infrastructure Master Key",
  "world_shape_matrix": "World Shape Matrix",
  "creative_builder_key": "Creative Builder Key",
  "incomplete_gear_logic": "Incomplete Gear Logic",
  "incomplete_precision_actuator": "Incomplete Precision Actuator",
  "incomplete_contraption_manifold": "Incomplete Contraption Manifold",
  "incomplete_overstressed_safety_valve": "Incomplete Overstressed Safety Valve",
  "incomplete_ritual_inscriber": "Incomplete Ritual Inscriber",
  "incomplete_source_coupler": "Incomplete Source Coupler",
  "incomplete_wixie_work_order": "Incomplete Wixie Work Order",
  "incomplete_archmage_spell_spine": "Incomplete Archmage Spell Spine",
  "incomplete_channel_marker": "Incomplete Channel Marker",
  "incomplete_pattern_bus_array": "Incomplete Pattern Bus Array",
  "incomplete_wireless_access_cipher": "Incomplete Wireless Access Cipher",
  "incomplete_me_singularity_lattice": "Incomplete Me Singularity Lattice",
  "incomplete_metallurgic_bus": "Incomplete Metallurgic Bus",
  "incomplete_energy_control_logic": "Incomplete Energy Control Logic",
  "incomplete_qio_sync_crystal": "Incomplete Qio Sync Crystal",
  "incomplete_nitro_flux_singularity": "Incomplete Nitro Flux Singularity",
  "incomplete_fluid_manifold": "Incomplete Fluid Manifold",
  "incomplete_steel_tooling_die": "Incomplete Steel Tooling Die",
  "incomplete_ore_drill_warrant": "Incomplete Ore Drill Warrant",
  "incomplete_supreme_frame_stamp": "Incomplete Supreme Frame Stamp",
  "incomplete_binding_contract": "Incomplete Binding Contract",
  "incomplete_familiars_permit": "Incomplete Familiars Permit",
  "incomplete_void_channel_key": "Incomplete Void Channel Key",
  "incomplete_spirit_network_crown": "Incomplete Spirit Network Crown",
  "incomplete_inferium_gene_sample": "Incomplete Inferium Gene Sample",
  "incomplete_bee_routing_tag": "Incomplete Bee Routing Tag",
  "incomplete_supremium_life_matrix": "Incomplete Supremium Life Matrix",
  "incomplete_worldseed_convergence_spore": "Incomplete Worldseed Convergence Spore",
  "incomplete_preservation_gasket": "Incomplete Preservation Gasket",
  "incomplete_market_crate_manifest": "Incomplete Market Crate Manifest",
  "incomplete_comfort_supply_contract": "Incomplete Comfort Supply Contract",
  "incomplete_server_catering_license": "Incomplete Server Catering License",
  "incomplete_ruined_blueprint_cache": "Incomplete Ruined Blueprint Cache",
  "incomplete_boss_trophy_writ": "Incomplete Boss Trophy Writ",
  "incomplete_wild_hunt_relic": "Incomplete Wild Hunt Relic",
  "incomplete_mythic_map_of_convergence": "Incomplete Mythic Map Of Convergence",
  "incomplete_lift_envelope_panel": "Incomplete Lift Envelope Panel",
  "incomplete_flight_stabilizer": "Incomplete Flight Stabilizer",
  "incomplete_cannon_synchronizer": "Incomplete Cannon Synchronizer",
  "incomplete_aerial_superiority_core": "Incomplete Aerial Superiority Core",
  "incomplete_compact_space_cell": "Incomplete Compact Space Cell",
  "incomplete_void_navigation_tablet": "Incomplete Void Navigation Tablet",
  "incomplete_voidbound_relay": "Incomplete Voidbound Relay",
  "incomplete_planar_singularity": "Incomplete Planar Singularity",
  "incomplete_roofing_supply_order": "Incomplete Roofing Supply Order",
  "incomplete_furniture_batch_ticket": "Incomplete Furniture Batch Ticket",
  "incomplete_compact_builder_rig": "Incomplete Compact Builder Rig",
  "incomplete_world_shape_matrix": "Incomplete World Shape Matrix"
};
StartupEvents.registry("item", event => {
  CV11_ITEMS.forEach(id => event.create(id).displayName(CV11_NAMES[id] || id).texture(`kubejs:item/${id}`))
  CV11_TRANSITIONALS.forEach(id => event.create(id, "create:sequenced_assembly").displayName(CV11_NAMES[id] || id).texture(`kubejs:item/${id}`))
})