// Convergence v0.25 - explicit core progression items.
(() => {
  const ITEMS = [
  "create_core_t1",
  "create_core_t2",
  "create_core_t3",
  "create_core_t4",
  "create_core_t5",
  "create_core_t6",
  "ars_core_t1",
  "ars_core_t2",
  "ars_core_t3",
  "ars_core_t4",
  "ars_core_t5",
  "ars_core_t6",
  "ae2_core_t1",
  "ae2_core_t2",
  "ae2_core_t3",
  "ae2_core_t4",
  "ae2_core_t5",
  "ae2_core_t6",
  "energy_core_t1",
  "energy_core_t2",
  "energy_core_t3",
  "energy_core_t4",
  "energy_core_t5",
  "energy_core_t6",
  "energy_core_t7",
  "industry_core_t1",
  "industry_core_t2",
  "industry_core_t3",
  "industry_core_t4",
  "industry_core_t5",
  "industry_core_t6",
  "occult_core_t1",
  "occult_core_t2",
  "occult_core_t3",
  "occult_core_t4",
  "occult_core_t5",
  "occult_core_t6",
  "agriculture_core_t1",
  "agriculture_core_t2",
  "agriculture_core_t3",
  "agriculture_core_t4",
  "agriculture_core_t5",
  "agriculture_core_t6",
  "agriculture_core_t7",
  "agriculture_core_t8",
  "cuisine_core_t1",
  "cuisine_core_t2",
  "cuisine_core_t3",
  "cuisine_core_t4",
  "exploration_core_t1",
  "exploration_core_t2",
  "exploration_core_t3",
  "exploration_core_t4",
  "aero_core_t1",
  "aero_core_t2",
  "aero_core_t3",
  "aero_core_t4",
  "aero_core_t5",
  "aero_core_t6",
  "travel_core_t1",
  "travel_core_t2",
  "travel_core_t3",
  "travel_core_t4",
  "infra_core_t1",
  "infra_core_t2",
  "infra_core_t3",
  "infra_core_t4"
];
  const NAMES = {
  "create_core_t1": "Create Core T1",
  "create_core_t2": "Create Core T2",
  "create_core_t3": "Create Core T3",
  "create_core_t4": "Create Core T4",
  "create_core_t5": "Create Core T5",
  "create_core_t6": "Create Core T6",
  "ars_core_t1": "Ars Nouveau Core T1",
  "ars_core_t2": "Ars Nouveau Core T2",
  "ars_core_t3": "Ars Nouveau Core T3",
  "ars_core_t4": "Ars Nouveau Core T4",
  "ars_core_t5": "Ars Nouveau Core T5",
  "ars_core_t6": "Ars Nouveau Core T6",
  "ae2_core_t1": "AE2 Core T1",
  "ae2_core_t2": "AE2 Core T2",
  "ae2_core_t3": "AE2 Core T3",
  "ae2_core_t4": "AE2 Core T4",
  "ae2_core_t5": "AE2 Core T5",
  "ae2_core_t6": "AE2 Core T6",
  "energy_core_t1": "Energy Core T1",
  "energy_core_t2": "Energy Core T2",
  "energy_core_t3": "Energy Core T3",
  "energy_core_t4": "Energy Core T4",
  "energy_core_t5": "Energy Core T5",
  "energy_core_t6": "Energy Core T6",
  "energy_core_t7": "Energy Core T7",
  "industry_core_t1": "Industry Core T1",
  "industry_core_t2": "Industry Core T2",
  "industry_core_t3": "Industry Core T3",
  "industry_core_t4": "Industry Core T4",
  "industry_core_t5": "Industry Core T5",
  "industry_core_t6": "Industry Core T6",
  "occult_core_t1": "Occultism Core T1",
  "occult_core_t2": "Occultism Core T2",
  "occult_core_t3": "Occultism Core T3",
  "occult_core_t4": "Occultism Core T4",
  "occult_core_t5": "Occultism Core T5",
  "occult_core_t6": "Occultism Core T6",
  "agriculture_core_t1": "Agriculture Core T1",
  "agriculture_core_t2": "Agriculture Core T2",
  "agriculture_core_t3": "Agriculture Core T3",
  "agriculture_core_t4": "Agriculture Core T4",
  "agriculture_core_t5": "Agriculture Core T5",
  "agriculture_core_t6": "Agriculture Core T6",
  "agriculture_core_t7": "Agriculture Core T7",
  "agriculture_core_t8": "Agriculture Core T8",
  "cuisine_core_t1": "Cuisine Core T1",
  "cuisine_core_t2": "Cuisine Core T2",
  "cuisine_core_t3": "Cuisine Core T3",
  "cuisine_core_t4": "Cuisine Core T4",
  "exploration_core_t1": "Exploration Core T1",
  "exploration_core_t2": "Exploration Core T2",
  "exploration_core_t3": "Exploration Core T3",
  "exploration_core_t4": "Exploration Core T4",
  "aero_core_t1": "Aero Core T1",
  "aero_core_t2": "Aero Core T2",
  "aero_core_t3": "Aero Core T3",
  "aero_core_t4": "Aero Core T4",
  "aero_core_t5": "Aero Core T5",
  "aero_core_t6": "Aero Core T6",
  "travel_core_t1": "Travel Core T1",
  "travel_core_t2": "Travel Core T2",
  "travel_core_t3": "Travel Core T3",
  "travel_core_t4": "Travel Core T4",
  "infra_core_t1": "Infrastructure Core T1",
  "infra_core_t2": "Infrastructure Core T2",
  "infra_core_t3": "Infrastructure Core T3",
  "infra_core_t4": "Infrastructure Core T4"
};
  StartupEvents.registry('item', event => {
    ITEMS.forEach(id => event.create(id).displayName(NAMES[id] || id).texture(`kubejs:item/${id}`))
  })
})();
