// Convergence v0.11 concise tooltips
ItemEvents.modifyTooltips(event => {
  event.add('kubejs:convergence_manual_binding', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:cross_discipline_adapter', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:modular_upgrade_schematic', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:midgame_convergence_ledger', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:late_game_integration_deed', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:endgame_assembly_mandate', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:universal_recipe_matrix', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:final_assembly_singularity', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:kinetic_magic_logistics_key', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:power_industry_void_key', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:bio_settlement_hunt_key', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:aero_travel_builder_key', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:worldforged_convergence_core', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:resonant_machine_frame', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:dimensional_matrix', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:unified_automation_core', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:source_treated_alloy', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:arcane_mechanism', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:runic_logic_processor', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:energized_control_circuit', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:industrial_servo', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:spirit_actuator', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:verdant_automation_core', Text.gray('Convergence progression component. See the Convergence Manual.'))
  event.add('kubejs:kinetic_calibrator', Text.gray('Create progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:stress_frame', Text.gray('Create progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:gear_logic', Text.gray('Create progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:casing_stamp', Text.gray('Create progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:belt_sync', Text.gray('Create progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:precision_actuator', Text.gray('Create progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:deploy_sequence_card', Text.gray('Create progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:factory_timing_unit', Text.gray('Create progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:contraption_manifold', Text.gray('Create progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:trainyard_route_token', Text.gray('Create progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:overstressed_safety_valve', Text.gray('Create progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_kinetic_key', Text.gray('Create progression part 12/12. See the Convergence Manual.'))
  event.add('kubejs:source_lens', Text.gray('Ars progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:glyphic_circuit', Text.gray('Ars progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:ritual_inscriber', Text.gray('Ars progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:spellbound_coil', Text.gray('Ars progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:imbuement_focus', Text.gray('Ars progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:source_coupler', Text.gray('Ars progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:sourcelink_regulator', Text.gray('Ars progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:spell_matrix', Text.gray('Ars progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:wixie_work_order', Text.gray('Ars progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:ritual_gateway_key', Text.gray('Ars progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:archmage_spell_spine', Text.gray('Ars progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_source_key', Text.gray('Ars progression part 12/12. See the Convergence Manual.'))
  event.add('kubejs:quartz_logic_wafer', Text.gray('AE2 progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:fluix_memory_lattice', Text.gray('AE2 progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:channel_marker', Text.gray('AE2 progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:me_cable_tag', Text.gray('AE2 progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:storage_cell_ticket', Text.gray('AE2 progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:pattern_bus_array', Text.gray('AE2 progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:crafting_coprocessor_matrix', Text.gray('AE2 progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:autocraft_policy_card', Text.gray('AE2 progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:wireless_access_cipher', Text.gray('AE2 progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:quantum_link_contract', Text.gray('AE2 progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:me_singularity_lattice', Text.gray('AE2 progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_logistics_key', Text.gray('AE2 progression part 12/12. See the Convergence Manual.'))
  event.add('kubejs:dielectric_regulator', Text.gray('Energy progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:capacitor_bank_coil', Text.gray('Energy progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:metallurgic_bus', Text.gray('Energy progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:enriched_energy_cell', Text.gray('Energy progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:alloy_reinforcement_ticket', Text.gray('Energy progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:energy_control_logic', Text.gray('Energy progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:battery_backplane', Text.gray('Energy progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:reactor_access_card', Text.gray('Energy progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:qio_sync_crystal', Text.gray('Energy progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:fusion_alignment_ring', Text.gray('Energy progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:nitro_flux_singularity', Text.gray('Energy progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_energy_key', Text.gray('Energy progression part 12/12. See the Convergence Manual.'))
  event.add('kubejs:treated_machine_plate', Text.gray('Industry progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:coke_calibrated_gear', Text.gray('Industry progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:fluid_manifold', Text.gray('Industry progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:conveyor_license', Text.gray('Industry progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:wirecoil_relay', Text.gray('Industry progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:steel_tooling_die', Text.gray('Industry progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:greenhouse_controller', Text.gray('Industry progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:factory_fluid_contract', Text.gray('Industry progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:ore_drill_warrant', Text.gray('Industry progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:machine_frame_charter', Text.gray('Industry progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:supreme_frame_stamp', Text.gray('Industry progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_industry_key', Text.gray('Industry progression part 12/12. See the Convergence Manual.'))
  event.add('kubejs:spirit_attunement_lens', Text.gray('Occult progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:chalked_servo', Text.gray('Occult progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:binding_contract', Text.gray('Occult progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:otherstone_manifold', Text.gray('Occult progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:iesnium_relay', Text.gray('Occult progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:familiars_permit', Text.gray('Occult progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:storage_spirit_writ', Text.gray('Occult progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:ritual_safety_clause', Text.gray('Occult progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:void_channel_key', Text.gray('Occult progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:dimensional_storage_oath', Text.gray('Occult progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:spirit_network_crown', Text.gray('Occult progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_void_key', Text.gray('Occult progression part 12/12. See the Convergence Manual.'))
  event.add('kubejs:growth_lattice', Text.gray('Nature progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:honeyed_logic_cell', Text.gray('Nature progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:inferium_gene_sample', Text.gray('Nature progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:botany_growth_plate', Text.gray('Nature progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:prosperity_cultivar', Text.gray('Nature progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:bee_routing_tag', Text.gray('Nature progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:tertium_greenhouse_writ', Text.gray('Nature progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:imperium_pollination_core', Text.gray('Nature progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:supremium_life_matrix', Text.gray('Nature progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:apiary_sovereignty_key', Text.gray('Nature progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:worldseed_convergence_spore', Text.gray('Nature progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_bio_key', Text.gray('Nature progression part 12/12. See the Convergence Manual.'))
  event.add('kubejs:kitchen_foundation_plan', Text.gray('Settlement progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:culinary_supply_manifest', Text.gray('Settlement progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:preservation_gasket', Text.gray('Settlement progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:settlement_ration_card', Text.gray('Settlement progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:stove_automation_token', Text.gray('Settlement progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:market_crate_manifest', Text.gray('Settlement progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:banquet_logistics_tag', Text.gray('Settlement progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:colony_storehouse_key', Text.gray('Settlement progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:comfort_supply_contract', Text.gray('Settlement progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:township_feast_writ', Text.gray('Settlement progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:server_catering_license', Text.gray('Settlement progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_settlement_key', Text.gray('Settlement progression part 12/12. See the Convergence Manual.'))
  event.add('kubejs:explorer_survey', Text.gray('Exploration progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:ancient_component_shard', Text.gray('Exploration progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:ruined_blueprint_cache', Text.gray('Exploration progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:dungeon_route_map', Text.gray('Exploration progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:relic_appraisal_tag', Text.gray('Exploration progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:boss_trophy_writ', Text.gray('Exploration progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:nether_campaign_token', Text.gray('Exploration progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:end_campaign_token', Text.gray('Exploration progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:wild_hunt_relic', Text.gray('Exploration progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:ancient_conquest_key', Text.gray('Exploration progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:mythic_map_of_convergence', Text.gray('Exploration progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_hunt_key', Text.gray('Exploration progression part 12/12. See the Convergence Manual.'))
  event.add('kubejs:balloon_rigging', Text.gray('Aero progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:burner_valve', Text.gray('Aero progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:lift_envelope_panel', Text.gray('Aero progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:wind_gyroscope', Text.gray('Aero progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:propeller_governor', Text.gray('Aero progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:flight_stabilizer', Text.gray('Aero progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:radar_transponder', Text.gray('Aero progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:avionics_backplane', Text.gray('Aero progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:cannon_synchronizer', Text.gray('Aero progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:sky_command_cipher', Text.gray('Aero progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:aerial_superiority_core', Text.gray('Aero progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_aero_key', Text.gray('Aero progression part 12/12. See the Convergence Manual.'))
  event.add('kubejs:ender_anchor_crystal', Text.gray('Travel progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:warp_attunement_rod', Text.gray('Travel progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:compact_space_cell', Text.gray('Travel progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:quantum_waystone_core', Text.gray('Travel progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:spatial_fold_lens', Text.gray('Travel progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:void_navigation_tablet', Text.gray('Travel progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:interdimensional_bus', Text.gray('Travel progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:planar_stabilizer', Text.gray('Travel progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:voidbound_relay', Text.gray('Travel progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:quantum_storage_seed', Text.gray('Travel progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:planar_singularity', Text.gray('Travel progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_dimension_key', Text.gray('Travel progression part 12/12. See the Convergence Manual.'))
  event.add('kubejs:mason_schematic', Text.gray('Building progression part 1/12. See the Convergence Manual.'))
  event.add('kubejs:decorative_fastener', Text.gray('Building progression part 2/12. See the Convergence Manual.'))
  event.add('kubejs:roofing_supply_order', Text.gray('Building progression part 3/12. See the Convergence Manual.'))
  event.add('kubejs:bridge_engineering_plan', Text.gray('Building progression part 4/12. See the Convergence Manual.'))
  event.add('kubejs:lamp_grid_relay', Text.gray('Building progression part 5/12. See the Convergence Manual.'))
  event.add('kubejs:furniture_batch_ticket', Text.gray('Building progression part 6/12. See the Convergence Manual.'))
  event.add('kubejs:gadget_calibration_plate', Text.gray('Building progression part 7/12. See the Convergence Manual.'))
  event.add('kubejs:structural_integrity_stamp', Text.gray('Building progression part 8/12. See the Convergence Manual.'))
  event.add('kubejs:compact_builder_rig', Text.gray('Building progression part 9/12. See the Convergence Manual.'))
  event.add('kubejs:infrastructure_master_key', Text.gray('Building progression part 10/12. See the Convergence Manual.'))
  event.add('kubejs:world_shape_matrix', Text.gray('Building progression part 11/12. See the Convergence Manual.'))
  event.add('kubejs:creative_builder_key', Text.gray('Building progression part 12/12. See the Convergence Manual.'))

  event.add('kubejs:bridge_matrix_t1', Text.gray('Bridge progression: early cross-path jump-starts'))
  event.add('kubejs:bridge_matrix_t2', Text.gray('Bridge progression: basic second-path entry'))
  event.add('kubejs:bridge_matrix_t3', Text.gray('Bridge progression: early automation crossover'))
  event.add('kubejs:bridge_matrix_t4', Text.gray('Bridge progression: midgame crossover'))
  event.add('kubejs:bridge_matrix_t5', Text.gray('Bridge progression: advanced automation crossover'))
  event.add('kubejs:bridge_matrix_t6', Text.gray('Bridge progression: late integration shortcut'))
  event.add('kubejs:bridge_matrix_t7', Text.gray('Bridge progression: endgame cross-path route'))
  event.add('kubejs:bridge_matrix_t8', Text.gray('Bridge progression: capstone jump-start route'))

})